//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialRate
    {
        public int Id { get; set; }
        public int sand { get; set; }
        public int cement { get; set; }
        public int steel { get; set; }
        public int bricks { get; set; }
        public string standard { get; set; }
    }
}
